version: '3'
services:
  camel-app:
    build: .
    container_name: camel-container
    image: meu-camel-app
    ports:
      - "8080:8080"
    volumes:
      - ./data/input:/app/data/input
      - ./data/output:/app/data/output